60 bug en la vista de costo de envio
Devs-Com/Stose pull request #61
Opened 2022-11-18 01:39 UTC by yeshua-aguilar

Se ha arreglado el bug de vista de la pestaña de costo de envío

2022-11-18 02:24 UTC, AnderMendoza reviewed
Revisar la parte responsive, se desproporciona el contenido y agrega un scroll horizontal.

![Captura de pantalla 2022-11-17 212158](https://user-images.githubusercontent.com/80181518/202602353-2b7b7235-e010-41c0-b473-6c4a61ef3d14.png)

Estoy atento a los cambios.

2022-11-22 00:47 UTC, yeshua-aguilar commented
responsive: 
![imagen](https://user-images.githubusercontent.com/81573986/203187217-b39e239e-1b6c-4c25-a658-0697cec32020.png)

2022-11-22 03:31 UTC, AnderMendoza requested changes
Aún se evidencia el error del desplazamiento lateral y el contenido fuera de su lugar.

![Captura de pantalla 2022-11-21 222946](https://user-images.githubusercontent.com/80181518/203214454-2ef6e189-f533-49f5-99d3-5e8690a6e2af.png)

2022-11-22 23:14 UTC, yeshua-aguilar commented
![imagen](https://user-images.githubusercontent.com/81573986/203439979-0b9191bc-2946-4f0f-8567-9abd77067cc8.png)

2022-11-26 00:33 UTC, AnderMendoza reviewed
Solo faltaría ajustar mejor el contenido del texto e imagen.

2022-12-03 21:41 UTC, merged