67 mostrar datos de la bd en la visa de inicio
Devs-Com/Stose pull request #77
Opened 2022-12-04 23:09 UTC by yeshua-aguilar

2022-12-05 23:27 UTC, AnderMendoza requested changes
No está arrojando los datos de los libros de la bd en la vista.

2022-12-05 23:35 UTC, AnderMendoza approved these changes
Ya se muestran los datos de la bd en la vista.

2022-12-08 03:20 UTC, AnderMendoza requested changes
Faltarían resolver unos puntos:
- [ ] Insertar el libro en oferta
- [ ] Mostrar el símbolo de soles (S/.) en los precios de todos los libros
- [ ] Quitar las estrellas de los libros destacados y libro en oferta. También en la vista de Tienda

2022-12-09 18:25 UTC, yeshua-aguilar commented
**SE HAN COLOCADO EL LIBRO OFERTA, SE QUITÓ LAS ESTRELLAS, Y SE COLOCÓ EL SÍMBOLO "S/."  A LOS PRECIOS**

![imagen](https://user-images.githubusercontent.com/81573986/206767511-44e3e9a7-49da-4565-b0e9-dbc271de2172.png)

![imagen](https://user-images.githubusercontent.com/81573986/206767975-4b8aae4f-13e4-4eff-88d1-a4acdc5c1769.png)

2022-12-10 02:27 UTC, yeshua-aguilar commented
**SE HAN VINCULADO CADA LIBRO CON SU DETALLE LIBRO EN LA VISTA**
![image](https://user-images.githubusercontent.com/81573986/206824229-64394fdc-607f-4eee-b50e-b768e242f80a.png)

**NOTA**
He intentado poner eso de libros relacionados y no me sale para nada. Que alguien se encargue y se explote la cabeza como hacerlo.

2022-12-10 23:01 UTC, AnderMendoza approved these changes
Se evidencia la correcta inserción de cada dato de un libro en la vista "detalle_libro"

2022-12-10 23:02 UTC, merged